### ISSUE TITLE
StatefulSet

### ISSUE THREAD

**Issue by chriskolenko** [grigorov/eventstore-helm#1]
Should Deployment be changed to statefulset?

**Comment by grigorov** [comment]
@chriskolenko 
You can use:
> --set persistence.enabled=true 

Or 
set values.yaml
`persistence:
  enabled: true
`

and comment:
`existingClaim`

**Comment by chriskolenko** [comment]
I'm using KubeSpray which I believe is Kube 1.9.x. StatefulSet is GA in 1.9+

I guess the question is, does this project need to support < 1.9?

**Comment by grigorov** [comment]
I have  many clusters on k8s 1.8, latest my k8s cluster - 1.9.5 (via kubespray). I can replace deployment on StatefulSet.

**Comment by grigorov** [comment]
https://github.com/grigorov/eventstore-helm/releases/tag/0.3.0
